### PR TITLE
created 3 plots

### PR DESCRIPTION
**Pull request by GachiRoss**
Speed box plot

Speed based on passengers

Distanced traveled based on passengers

### CODE REVIEW

**Comment by Nicklason** [comment]
I think an average speed based on trip distance would be very nice to see

**Review by Nicklason — COMMENTED** [review]
Maybe we should filter out taxi rides with 0 passengers?

**Review by Samirez — APPROVED** [review]
just add filter with 0 passengers and it's ready to be merged

**Comment by vimian** [comment]
image
image
image

**Comment by Samirez** [comment]
change this to fit the new format we divided the files into before it can be merged

**Pull request merged**
